In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HousePricePrediction.csv')

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [4]:
df.drop('Id', axis = 1, inplace = True)

In [5]:
df.drop('MSZoning', axis = 1, inplace = True)

In [6]:
df.head()

,MSSubClass,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [7]:
df.isnull().sum()

MSSubClass         0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [8]:
df.isnull().mean()*100

MSSubClass       0.000000
LotArea          0.000000
LotConfig        0.000000
BldgType         0.000000
OverallCond      0.000000
YearBuilt        0.000000
YearRemodAdd     0.000000
Exterior1st      0.034258
BsmtFinSF2       0.034258
TotalBsmtSF      0.034258
SalePrice       49.982871
dtype: float64

In [9]:
df['LotConfig']. value_counts()
df['BldgType']. value_counts()
# df['Exterior1st']. value_counts()

BldgType
1Fam      2425
TwnhsE     227
Duplex     109
Twnhs       96
2fmCon      62
Name: count, dtype: int64

In [10]:
df.isnull().sum()

MSSubClass         0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [11]:
df.fillna(method = 'bfill', inplace = True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_4912\3982322604.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill', inplace = True)

In [12]:
df.isnull().sum()

MSSubClass         0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        0
BsmtFinSF2         0
TotalBsmtSF        0
SalePrice       1459
dtype: int64

In [13]:
X = df[['MSSubClass','LotArea','LotConfig','BldgType','OverallCond','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']]
X.head()

,MSSubClass,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF
0,60,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0
1,20,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0
2,60,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0
3,70,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0
4,60,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0

In [14]:
y = df['SalePrice']
y.head()

0    208500.0
1    181500.0
2    223500.0
3    140000.0
4    250000.0
Name: SalePrice, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [16]:
print('X_train: ',X_train.shape)
print('X_test: ',X_test.shape)
print('y_train: ',y_train.shape)
print('y_test: ',y_test.shape)

X_train:  (2335, 10)
X_test:  (584, 10)
y_train:  (2335,)
y_test:  (584,)

In [17]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_Area = si.fit_transform(X_train[['LotArea']])
X_test_Area = si.fit_transform(X_test[['LotArea']])

In [18]:
X_train_Area

array([[18030.],
       [12919.],
       [ 3180.],
       ...,
       [ 2308.],
       [33983.],
       [ 9600.]])

In [19]:
X_test_Area

array([[ 8520.],
       [ 8088.],
       [ 9842.],
       [16451.],
       [ 9742.],
       [ 7500.],
       [15564.],
       [ 8536.],
       [10192.],
       [ 9170.],
       [ 1869.],
       [ 8333.],
       [ 6120.],
       [ 3182.],
       [17242.],
       [12680.],
       [ 9060.],
       [ 4435.],
       [11613.],
       [ 8000.],
       [ 2160.],
       [ 9906.],
       [10206.],
       [ 8012.],
       [18261.],
       [ 8172.],
       [10890.],
       [ 7518.],
       [ 4426.],
       [ 8872.],
       [ 6155.],
       [ 9000.],
       [ 9101.],
       [ 8765.],
       [21750.],
       [ 7200.],
       [11235.],
       [10240.],
       [ 8125.],
       [16492.],
       [ 9317.],
       [ 9920.],
       [ 7903.],
       [ 8089.],
       [ 8487.],
       [ 9144.],
       [13837.],
       [ 9525.],
       [ 3068.],
       [ 2280.],
       [ 7875.],
       [ 8127.],
       [ 9060.],
       [ 8396.],
       [12046.],
       [ 9724.],
       [ 8366.],
       [ 9928.],
       [ 4060.],
       [ 3672.],
       [ 5000.],
       [ 7032.],
       [ 9786.],
       [10800.],
       [12144.],
       [11880.],
       [10120.],
       [11512.],
       [ 8800.],
       [ 3675.],
       [12760.],
       [13360.],
       [ 8146.],
       [ 8285.],
       [ 9920.],
       [ 1484.],
       [18044.],
       [15523.],
       [10552.],
       [ 9196.],
       [ 7700.],
       [ 9738.],
       [ 9000.],
       [18890.],
       [11060.],
       [12000.],
       [13101.],
       [12299.],
       [17755.],
       [12376.],
       [ 3087.],
       [26178.],
       [12350.],
       [ 7200.],
       [ 7200.],
       [ 7200.],
       [ 7758.],
       [ 9803.],
       [ 5400.],
       [10800.],
       [ 7804.],
       [17485.],
       [ 9000.],
       [ 4671.],
       [ 8899.],
       [ 4270.],
       [ 5500.],
       [ 1680.],
       [ 3180.],
       [13159.],
       [ 9316.],
       [11700.],
       [ 9638.],
       [ 9680.],
       [ 6373.],
       [ 3940.],
       [ 1680.],
       [11839.],
       [17778.],
       [ 8158.],
       [11100.],
       [11957.],
       [ 9084.],
       [10594.],
       [14112.],
       [ 8398.],
       [11923.],
       [ 8500.],
       [18275.],
       [ 8688.],
       [ 7056.],
       [ 8220.],
       [ 9571.],
       [ 1596.],
       [ 7745.],
       [11875.],
       [17433.],
       [ 9066.],
       [ 6240.],
       [14572.],
       [ 8076.],
       [ 9100.],
       [ 6120.],
       [18000.],
       [11606.],
       [ 7937.],
       [ 8400.],
       [ 8750.],
       [ 6012.],
       [ 3480.],
       [ 4400.],
       [ 9600.],
       [ 1526.],
       [13162.],
       [13072.],
       [11200.],
       [ 5436.],
       [14598.],
       [11650.],
       [ 7861.],
       [11250.],
       [11500.],
       [ 8400.],
       [ 2500.],
       [11388.],
       [ 9675.],
       [15384.],
       [ 7308.],
       [ 4800.],
       [ 8158.],
       [13651.],
       [ 7703.],
       [17671.],
       [ 7476.],
       [ 6120.],
       [ 7030.],
       [32668.],
       [11080.],
       [ 7000.],
       [ 1890.],
       [11170.],
       [ 5250.],
       [12887.],
       [ 2645.],
       [14082.],
       [17871.],
       [ 1470.],
       [10454.],
       [ 4712.],
       [13200.],
       [ 8842.],
       [11475.],
       [ 9308.],
       [ 4500.],
       [11625.],
       [11317.],
       [ 8520.],
       [12720.],
       [10998.],
       [ 9130.],
       [ 8910.],
       [ 9771.],
       [ 7200.],
       [18450.],
       [ 8775.],
       [21872.],
       [11792.],
       [10090.],
       [ 3907.],
       [12304.],
       [13474.],
       [ 9600.],
       [ 9863.],
       [14778.],
       [ 5005.],
       [11248.],
       [12393.],
       [ 6171.],
       [ 4224.],
       [13472.],
       [ 9200.],
       [17043.],
       [ 6120.],
       [ 6854.],
       [ 8172.],
       [ 5720.],
       [11694.],
       [ 2665.],
       [10357.],
       [12366.],
       [ 8145.],
       [11198.],
       [11050.],
       [15300.],
       [ 8750.],
       [ 7440.],
       [11361.],
       [ 6993.],
       [ 9350.],
       [ 9143.],
       [15750.],
       [ 8334.],
       [14175.],
       [11250.],
       [12606.],
       [ 8731.],
       [10421.],
       [10475.],
       [10324.],
       [14149.],
       [ 7200.],
       [ 6125.],
       [ 9017.],
       [ 9100.],
       [10625.],
       [13704.],
       [ 7420.],
       [11050.],
       [ 9450.],
       [ 4571.],
       [ 8800.],
       [15593.],
       [11250.],
       [10410.],
       [ 1950.],
       [ 6000.],
       [16387.],
       [11727.],
       [ 9490.],
       [ 4385.],
       [ 7942.],
       [12702.],
       [ 8556.],
       [ 9416.],
       [11050.],
       [ 7020.],
       [ 6858.],
       [ 9768.],
       [ 7314.],
       [10574.],
       [ 9297.],
       [11100.],
       [ 7244.],
       [ 7500.],
       [ 7008.],
       [11327.],
       [12250.],
       [ 3072.],
       [ 3675.],
       [ 6204.],
       [ 7340.],
       [24682.],
       [12936.],
       [10386.],
       [14565.],
       [13618.],
       [ 8777.],
       [14210.],
       [ 7777.],
       [16033.],
       [ 7800.],
       [ 9735.],
       [ 8125.],
       [16300.],
       [ 1733.],
       [ 9316.],
       [46589.],
       [ 3830.],
       [22002.],
       [10400.],
       [32463.],
       [ 8927.],
       [ 8723.],
       [ 3435.],
       [ 8385.],
       [ 9720.],
       [ 2104.],
       [ 3182.],
       [ 3768.],
       [11354.],
       [50271.],
       [10533.],
       [ 2280.],
       [14235.],
       [ 9340.],
       [ 8450.],
       [12461.],
       [ 2268.],
       [ 8198.],
       [ 9750.],
       [11855.],
       [ 3072.],
       [10655.],
       [13615.],
       [17169.],
       [11345.],
       [16259.],
       [ 3182.],
       [10179.],
       [ 7500.],
       [10832.],
       [ 9100.],
       [13053.],
       [15218.],
       [10625.],
       [10800.],
       [10207.],
       [16692.],
       [13710.],
       [ 8658.],
       [ 7000.],
       [ 9512.],
       [11600.],
       [ 7733.],
       [13907.],
       [10456.],
       [10143.],
       [10800.],
       [ 3000.],
       [ 7200.],
       [13501.],
       [10382.],
       [ 1900.],
       [11778.],
       [ 7801.],
       [ 8520.],
       [14303.],
       [ 3604.],
       [14541.],
       [ 8000.],
       [16669.],
       [ 8475.],
       [15306.],
       [ 9000.],
       [ 5160.],
       [ 8125.],
       [ 8730.],
       [ 9144.],
       [ 8965.],
       [10320.],
       [ 7038.],
       [ 7000.],
       [11950.],
       [ 6000.],
       [11988.],
       [ 9230.],
       [ 4761.],
       [ 7931.],
       [ 8000.],
       [10732.],
       [ 8450.],
       [13125.],
       [ 7830.],
       [10625.],
       [10793.],
       [10171.],
       [15256.],
       [11070.],
       [ 6000.],
       [10440.],
       [13355.],
       [10632.],
       [ 8499.],
       [ 7200.],
       [15295.],
       [ 9600.],
       [11447.],
       [ 9636.],
       [ 6240.],
       [10429.],
       [11332.],
       [ 7706.],
       [10000.],
       [11355.],
       [ 6300.],
       [ 9649.],
       [11767.],
       [ 9278.],
       [ 3701.],
       [31250.],
       [ 7024.],
       [10800.],
       [ 8160.],
       [ 5000.],
       [ 9280.],
       [12244.],
       [10170.],
       [14054.],
       [12692.],
       [11660.],
       [ 1974.],
       [10236.],
       [21000.],
       [ 8987.],
       [ 8814.],
       [15387.],
       [15611.],
       [ 6956.],
       [ 1879.],
       [ 4435.],
       [11380.],
       [ 7226.],
       [ 7584.],
       [ 7984.],
       [11920.],
       [ 8064.],
       [ 8967.],
       [ 8816.],
       [11316.],
       [ 5400.],
       [10920.],
       [ 8924.],
       [13214.],
       [13215.],
       [10773.],
       [ 9156.],
       [ 9600.],
       [ 7862.],
       [12328.],
       [10846.],
       [ 7500.],
       [ 8926.],
       [ 8640.],
       [14418.],
       [ 6978.],
       [ 8521.],
       [ 6120.],
       [12172.],
       [ 2289.],
       [ 9942.],
       [10440.],
       [14762.],
       [ 9717.],
       [ 7728.],
       [ 8777.],
       [53227.],
       [11765.],
       [ 8593.],
       [ 8232.],
       [ 2308.],
       [12633.],
       [11419.],
       [12772.],
       [ 7851.],
       [11700.],
       [20431.],
       [31220.],
       [18265.],
       [ 4500.],
       [ 9759.],
       [13825.],
       [11645.],
       [ 2998.],
       [17500.],
       [ 5062.],
       [10050.],
       [ 9375.],
       [11782.],
       [ 8050.],
       [ 7750.],
       [ 9045.],
       [14311.],
       [14948.],
       [ 9000.],
       [12671.],
       [10890.],
       [12615.],
       [ 6060.],
       [ 9750.],
       [10541.],
       [ 9965.],
       [10482.],
       [12350.],
       [18559.],
       [14419.],
       [13600.],
       [ 9434.],
       [ 8251.],
       [13770.],
       [ 8712.],
       [ 3180.],
       [ 7920.],
       [ 4058.],
       [10400.],
       [ 9375.],
       [ 3811.],
       [ 8147.],
       [10530.],
       [ 1782.],
       [ 7500.],
       [11841.],
       [ 9900.],
       [ 9671.],
       [ 2280.],
       [ 6240.],
       [10152.],
       [39104.],
       [ 9245.],
       [ 9830.],
       [10134.],
       [ 2645.],
       [ 5000.],
       [10750.],
       [ 8633.],
       [ 5520.],
       [10927.],
       [11751.],
       [ 8100.],
       [14836.],
       [ 9590.],
       [13265.],
       [10320.],
       [10943.],
       [ 8461.],
       [10593.],
       [16381.],
       [ 5105.],
       [11175.],
       [10200.],
       [13515.],
       [33120.],
       [ 9770.],
       [ 9000.],
       [ 5400.],
       [10011.],
       [ 9723.],
       [ 9158.],
       [ 8339.],
       [11478.],
       [10437.],
       [11664.],
       [10637.],
       [ 8640.],
       [ 4590.],
       [12728.],
       [11250.],
       [ 9780.],
       [15676.],
       [13830.],
       [ 6931.],
       [18600.],
       [10800.],
       [10440.],
       [11800.]])

In [20]:
X_train

,MSSubClass,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF
1173,50,18030,Inside,1Fam,6,1946,1994,MetalSd,469.0,1598.0
898,20,12919,Inside,1Fam,5,2009,2010,VinylSd,0.0,2330.0
1364,160,3180,Inside,TwnhsE,5,2005,2005,MetalSd,0.0,600.0
563,50,21780,Inside,1Fam,7,1918,1950,Wd Sdng,0.0,1163.0
2208,20,26073,CulDSac,1Fam,5,1956,1956,BrkFace,0.0,1898.0
...,...,...,...,...,...,...,...,...,...,...
763,60,9430,Inside,1Fam,5,1999,1999,VinylSd,0.0,1252.0
835,20,9600,Inside,1Fam,7,1950,1995,VinylSd,0.0,1067.0
1653,160,2308,FR2,TwnhsE,5,1976,1976,Plywood,0.0,804.0
2607,20,33983,Inside,1Fam,6,1977,1994,Plywood,0.0,1160.0
2732,20,9600,Inside,1Fam,6,1961,1990,WdShing,0.0,1251.0

In [21]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['1Fam', 'TwnhsE','Duplex','Twnhs','2fmCon']])
X_train_Bldg = oe.fit_transform(X_train[['BldgType']])
X_test_Bldg = oe.fit_transform(X_test[['BldgType']])

In [22]:
X_train_Bldg
# X_test_Bldg

array([[0.],
       [0.],
       [1.],
       ...,
       [1.],
       [0.],
       [0.]])

In [23]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder(drop='first',sparse_output=False)
X_train_lc_ext = oe.fit_transform(X_train[['LotConfig', 'Exterior1st']])
X_test_lc_ext = oe.fit_transform(X_test[['LotConfig', 'Exterior1st']])

In [24]:
X_train_lc_ext
X_test_lc_ext

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
X_train_MSC = X_train.drop(columns = ['LotArea','LotConfig','BldgType','OverallCond','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_MSC = X_test.drop(columns = ['LotArea','LotConfig','BldgType','OverallCond','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_MSC

array([[ 50],
       [ 20],
       [160],
       ...,
       [160],
       [ 20],
       [ 20]], dtype=int64)

In [26]:
X_train_OC = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_OC = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_OC

array([[6],
       [5],
       [5],
       ...,
       [5],
       [6],
       [6]], dtype=int64)

In [27]:
X_train_YB = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_YB = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearRemodAdd','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_YB

array([[1946],
       [2009],
       [2005],
       ...,
       [1976],
       [1977],
       [1961]], dtype=int64)

In [28]:
X_train_YRA = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_test_YRA = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','Exterior1st','BsmtFinSF2','TotalBsmtSF']).values
X_train_YRA

array([[1994],
       [2010],
       [2005],
       ...,
       [1976],
       [1994],
       [1990]], dtype=int64)

In [29]:
X_train_BSMT = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2']).values
X_test_BSMT = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','BsmtFinSF2']).values
X_train_BSMT

array([[1598.],
       [2330.],
       [ 600.],
       ...,
       [ 804.],
       [1160.],
       [1251.]])

In [30]:
X_train_BSMT2 = X_train.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','TotalBsmtSF']).values
X_test_BSMT2 = X_test.drop(columns = ['MSSubClass','LotArea','LotConfig','OverallCond','BldgType','YearBuilt','YearRemodAdd','Exterior1st','TotalBsmtSF']).values
X_train_BSMT2

array([[469.],
       [  0.],
       [  0.],
       ...,
       [  0.],
       [  0.],
       [  0.]])

In [31]:
X_train

,MSSubClass,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF
1173,50,18030,Inside,1Fam,6,1946,1994,MetalSd,469.0,1598.0
898,20,12919,Inside,1Fam,5,2009,2010,VinylSd,0.0,2330.0
1364,160,3180,Inside,TwnhsE,5,2005,2005,MetalSd,0.0,600.0
563,50,21780,Inside,1Fam,7,1918,1950,Wd Sdng,0.0,1163.0
2208,20,26073,CulDSac,1Fam,5,1956,1956,BrkFace,0.0,1898.0
...,...,...,...,...,...,...,...,...,...,...
763,60,9430,Inside,1Fam,5,1999,1999,VinylSd,0.0,1252.0
835,20,9600,Inside,1Fam,7,1950,1995,VinylSd,0.0,1067.0
1653,160,2308,FR2,TwnhsE,5,1976,1976,Plywood,0.0,804.0
2607,20,33983,Inside,1Fam,6,1977,1994,Plywood,0.0,1160.0
2732,20,9600,Inside,1Fam,6,1961,1990,WdShing,0.0,1251.0

In [32]:
X_train_transformed = np.concatenate((X_train_MSC, X_train_Area,X_train_lc_ext , X_train_Bldg,
                                      X_train_OC,X_train_YB,X_train_YRA ,X_train_BSMT2, X_train_BSMT ), axis =1)

X_test_transformed = np.concatenate((X_test_MSC, X_test_Area, X_test_lc_ext , X_test_Bldg,
                                     X_test_OC, X_test_YB, X_test_YRA , X_test_BSMT2, X_test_BSMT ), axis =1)
X_train_transformed

array([[5.0000e+01, 1.8030e+04, 0.0000e+00, ..., 1.9940e+03, 4.6900e+02,
        1.5980e+03],
       [2.0000e+01, 1.2919e+04, 0.0000e+00, ..., 2.0100e+03, 0.0000e+00,
        2.3300e+03],
       [1.6000e+02, 3.1800e+03, 0.0000e+00, ..., 2.0050e+03, 0.0000e+00,
        6.0000e+02],
       ...,
       [1.6000e+02, 2.3080e+03, 0.0000e+00, ..., 1.9760e+03, 0.0000e+00,
        8.0400e+02],
       [2.0000e+01, 3.3983e+04, 0.0000e+00, ..., 1.9940e+03, 0.0000e+00,
        1.1600e+03],
       [2.0000e+01, 9.6000e+03, 0.0000e+00, ..., 1.9900e+03, 0.0000e+00,
        1.2510e+03]])

# Column Transformation

In [33]:
from sklearn.compose import ColumnTransformer

In [34]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['LotArea']),
    ('tnf2',OrdinalEncoder(categories=[['1Fam', 'TwnhsE','Duplex','Twnhs','2fmCon']]),['BldgType']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['LotConfig', 'Exterior1st'])
],remainder='passthrough')

In [35]:
transformer.fit_transform(X_train)

array([[1.8030e+04, 0.0000e+00, 0.0000e+00, ..., 1.9940e+03, 4.6900e+02,
        1.5980e+03],
       [1.2919e+04, 0.0000e+00, 0.0000e+00, ..., 2.0100e+03, 0.0000e+00,
        2.3300e+03],
       [3.1800e+03, 1.0000e+00, 0.0000e+00, ..., 2.0050e+03, 0.0000e+00,
        6.0000e+02],
       ...,
       [2.3080e+03, 1.0000e+00, 0.0000e+00, ..., 1.9760e+03, 0.0000e+00,
        8.0400e+02],
       [3.3983e+04, 0.0000e+00, 0.0000e+00, ..., 1.9940e+03, 0.0000e+00,
        1.1600e+03],
       [9.6000e+03, 0.0000e+00, 0.0000e+00, ..., 1.9900e+03, 0.0000e+00,
        1.2510e+03]])